### ISSUE TITLE
Remove static from GeometryWriter methods

### ISSUE THREAD

**Issue by neilireson** [ngageoint/simple-features-wkt-java#2]
I need to transform the coordinates when writing a point using the "writePoint" method. However because all the methods are static I have to copy and alter the whole class rather than just being able to create a subclass and @Override that individual method.

I'm not sure having everything as static is particularly advantageous for a class of interacting methods and you could always use a global static variable (i.e. public static final GeometryWriter INSTANCE = new GeomatryWriter();) to provide a single entry point, which would kind of mimic the current use.

**Comment by bosborn** [comment]
Made some [updates to the writer and reader](https://github.com/ngageoint/simple-features-wkt-java/commit/5587c2fefc858af2713d8b830a22cf4ca1e75f4e) on the [develop branch](https://github.com/ngageoint/simple-features-wkt-java/tree/develop) that should work for you.

The [projections library](https://github.com/ngageoint/simple-features-proj-java) will also do coordinate transformations.  If you don't need inline coordinate transformations, you can transform any geometry to the desired projection before writing to the well-known text.
